development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['development_db_name'] %>
  pool: 5
  username: <%= ENV['development_db_username'] %>
  password: <%= ENV['development_db_password'] %>

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database:  <%= ENV['test_db_name'] %>
  pool: 5
  username: <%= ENV['test_db_username'] %>
  password:  <%= ENV['test_db_password'] %>

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database:  <%= ENV['production_db_name'] %>
  pool: 5
  username: <%= ENV['production_db_username'] %>
  password:  <%= ENV['production_db_password'] %>
